### ISSUE TITLE
Review Feedback

### ISSUE THREAD

**Issue by GraceJansen** [OpenLiberty/draft-guide-reactive-rest-client#56]
- [x] Spelling mistake in first paragraph of "what you'll learn" section - "via HTTP protocol and allowes developers to concisely" --> allows is spelt incorrectly.

- [x] The term "reactive programming" is used in this first paragraph but no link or definition/explanation is given for this -> assumed knowledge. Should we be defining or at least maming reference to RXJava as part of this section, as it's mentioned later on in this guide?

- [ ] Asynchronous messaging is referred to but no link to reactive made or benefits given of using this over synchronous. Maybe nice to have a sentence from the "Asynchronous messaging between microservices" section of the Creating reactive Java microservices guide?

- [x] lots of whitespace after pre-req section, not sure if this is only on staging server but can we make sure this is gone when published please?

- [x] Would maybe suggest changing this sentence ". Also register the type of object that you want inside the client invocation." to "You'll also need to register.........."

- [x] I think there's a mistake in this sentence "Sometimes there are scenarios where a producer will generate more data than the consumers and handle" --> I think it should end with "consumers can handle" instead of "and"

- [x] Think there should be a comma after Thus in this sentence: "Thus any required processing of data will be performed in the subscribe() method."

- [x] Should this second reference to holder ("The temporary holder is used") also be formatted differently to plain text, like the first reference in the sentence prior to this?

**Comment by TiagoF99** [comment]
>  lots of whitespace after pre-req section, not sure if this is only on staging server but can we make sure this is gone when published please?
- This is by design, by the UI team. There is an issue here (https://github.com/OpenLiberty/openliberty.io/issues/1693) which outlines the concerns you have brought up.

**Comment by TiagoF99** [comment]
- Addressed comments with this PR: https://github.com/OpenLiberty/draft-guide-reactive-rest-client/pull/57/
