### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/draft-guide-reactive-rest-client#59]
A couple of comments from @andymc12 (I needed to check my understanding with him during my review):

**InventoryClient.java** is fine technically, but I think it tries to reuse code too much which (IMO) makes it harder for readers to follow.
For example, there are too many methods that should be condensed. like

```
private WebTarget target;
    public InventoryClient() {
        this.target = null;
    }
    public List<String> getSystems() {
        return iBuilder(ClientBuilder
                .newClient()
                .target(baseUri)
                .path("/inventory/systems"))
                .get(new GenericType<List<String>>(){});
    }
    public CompletionStage<Properties> getSystem(String hostname) {
        return iBuilder(webTarget().path(hostname))
            .rx()
            .get(Properties.class);
    }
    private Invocation.Builder iBuilder(WebTarget target) {
        return target
            .request()
            .header(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON);
    }
    private WebTarget webTarget() {
        if (this.target == null) {
            this.target = ClientBuilder
                .newClient()
                .target(baseUri)
                .path("/inventory/systems");
        }
        return this.target;
    }
```
could be shortened to:
```
    public List<String> getSystems() {
        return ClientBuilder.newClient()
                            .target(baseUri)
                            .path("/inventory/systems")
                            .request()
                            .header(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON)
                            .get(new GenericType<List<String>>(){});
    }
    public CompletionStage<Properties> getSystem(String hostname) {
        return ClientBuilder.newClient()
                            .target(baseUri)
                            .path(hostname)
                            .request()
                            .header(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON)
                            .rx()
                            .get(Properties.class);
    }
```

**QueryResource.java** - it is using MP Rest Client APIs, but shouldn't.  This guide should be about the JAX-RS Client, not MP Rest Client.

I marked the lines to remove in the code below:

```
import javax.ws.rs.core.MediaType;
import org.eclipse.microprofile.rest.client.inject.RestClient; // REMOVE
import io.openliberty.guides.query.client.InventoryClient;
@ApplicationScoped
@Path("/query")
public class QueryResource {
    @Inject
    @RestClient //REMOVE
    private InventoryClient inventoryClient;
```

**Comment by TiagoF99** [comment]
Hi @lauracowen and @andymc12 , thank you for the feedback! @andymc12 how do you suggest I log the exception. I know our original plan was to have the `start/query` of this guide match with the `finish/query` of the async guide (https://github.com/OpenLiberty/guide-microprofile-rest-client-async/blob/master/finish/query/src/main/java/io/openliberty/guides/query/QueryResource.java) and that guide does not log the exception. Im not sure if that is a change that we want to make as well?

**Comment by andymc12** [comment]
> how do you suggest I log the exception?

Whatever is easiest - maybe `ex.printStackTrace()`.  The idea is just to make sure that the user does something with the exception.  

> I know our original plan was to have the start/query of this guide match with the finish/query of the async guide (https://github.com/OpenLiberty/guide-microprofile-rest-client-async/blob/master/finish/query/src/main/java/io/openliberty/guides/query/QueryResource.java) and that guide does not log the exception. Im not sure if that is a change that we want to make as well?

Yes, that's probably a good idea.  


Other than logging the exception, the changes in PR #60 look good to me.  Thanks for the quick turnaround!

**Comment by lauracowen** [comment]
Thanks for the explanation about CXF/Jersey @andymc12 .

@TiagoF99 I'm still reviewing the guide and will get my feedback to you by the end of today. As part of that I'm currently re-drafting the intro so that it states more clearly up-front what the reader will learn from the guide, as it currently isn't quite as immediately clear as it could be (it took me a bit of reading to get my head around what the guide was doing). I've included a bit of Andy's info from above in that.

**Comment by AustinSeto** [comment]
#60 approved and merged, closing this
