### ISSUE TITLE
Laura's review feedback

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/draft-guide-reactive-rest-client#61]
Interesting guide and overall follows through nicely. It took me a while to understand what was going to happen in the guide so I've given an re-draft of the intro below. The guide was also a bit static in places where the reader was expected to read despite having been promised they would "create". I discussed with Gilbert and he'll discuss with you (more details below). In the main explanatory sections, I've edited the text down in places so it's more concise.

Title/Abstract
- [x] Title and abstract need to have a "the" or "a" (as appropriate) before "reactive JAX-RS client".
- [x] Abstract: "Learn how to use reactive JAX-RS client to invoke RESTful microservices over HTTP asynchronously." -> "Learn how to write a reactive JAX-RS client to asynchronously call RESTful microservices over HTTP."

Intro section
- [x] The intro isn't far off but I couldn't quickly grasp what the aim of the guide is. It needs to be a little more direct and immediate (but get someone to check it's technical accuracy) like this:

  "You'll learn how to create a reactive JAX-RS client application using two different JAX-RS reactive providers, Apache CXF and Eclipse Jersey. The JAX-RS client is an API used to communicate with RESTful web services. The API makes it very easy to consume a web service exposed using the HTTP protocol and means that you can efficiently implement client-side solutions. The reactive client extension to JAX-RS is an API that enables you to use the reactive programming model when using the JAX-RS client.

  Reactive programming is an extension of asynchronous programming and focuses on the flow of data through data streams. Reactive application process data when it becomes available and responds to requests as soon as the processing is complete; the request and response to the application are decoupled so that the application is not blocked from responding to other requests in the meantime. Reactive applications can run faster than synchronous applications, which provides a much smoother user experience.

  The application in this guide demonstrates how the JAX-RS client accesses remote RESTful services using asynchronous method calls. You'll first take a look at the supplied client application which uses CXF, the JAX-RS reactive provider used by default in Open Liberty, then you'll modify the client application to instead use Jersey, an alternative JAX-RS reactive provider. Both CXF and Jersey provide third-party reactive libraries, including RxJava, and have been tested for use in Open Liberty.

  The application you will be working with consists….etc (as you have now with the diagram)."
  - [x] Remove the sentence starting "The implementations of the application…." (that goes without saying - it's the standard guide format we use).
  - [x] Just keep the sentences about MicroProfile and the link to the guide.

Some notes from the original intro (in case they're applicable more generally):
- [ ] "default JAX-RS client" - default in what context? I think this should actually say "the reactive client provided by JAX-RS" or similar. Or introduce it more as "JAX-RS provides a reactive client, which is an API that is used to communicate…".
- [x] "client side solutions" -> "client-side solutions"
- [x] Try to avoid speaking in the third person about "users". Talk to the reader as if it's aimed at them personally; eg "enables you to efficiently implement client-side solutions".
- [x] "solutions" sounds a bit business-y - maybe "client-side applications" is more developer-y?
- [x] "utilize" -> "use" - don't use fancy words when simple ones will do.
- [ ] " Instead of using elementary, single-use asynchronous solutions, you will use asynchronous data streams to transport data." - no idea what this means or is saying...I think it needs to be clearer. :) I tried rewording the sentences around this to be less jargon-y and also to be more like to the similar explanations in the first reactive guide (without going into as much detail as that guide does). See what you think.
- [x] "you will learn the benefits of using the Observable class over the more traditional CompletionStage interface, like more scalable implementation. " Don't need to go into this much detail so early on - can come to that later in the relevant parts of the guide. Another point I wrote down during my initial read through was: Think the phrasing of this should be changed as it sounds dismissive of CompletionStage which we do talk about in lots of places (most recently Emily and Grace, our main MicroProfile and reactive dev advocates do in [this article](https://developer.ibm.com/articles/develop-reactive-microservices-with-microprofile/)), although there are more benefits with Observable or other APIs so it's a balancing act to word this kind of thing.

Creating a web client using the default JAX-RS API section
- [x] This heading doesn't make sense because the start of the section says that the implementation is already provided, and in the rest of the section, the reader is not expected to do anything other than read. Ideally, we'd have them actually create the two classes here (as normally happens in the guides), then update the two classes in the "Update…" section. I checked this with Gilbert and we can do this in a more interactive way by inserting an extra build step for the first version of the app. I'm going to assume that for the rest of this review feedback.
- [x] Change the section heading to "Creating a web client using the CXF reactive provider" - "default JAX-RS API" is ambiguous (based on what Andy said it's the default in Liberty but is just one of many JAX-RS APIs). Just be more explicit about what this section is about.
- [x] Then after the `start` directory sentence, modify the rest of the section slightly to:

  "The CXF reactive provider is provided by default in Open Liberty so that you can write application using reactive APIs like RxJava. Create an InventoryClient class which is used to retrieve the inventory data, and a QueryResource class, which queries data from the Inventory service.

  ACTION BUTTON for InventoryClient class here.

  The getSystem() method returns the CompletionStage interface. This interface represents a unit or stage of a computation and, when the associated computation completes, the value contained can be retrieved. The rx() method calls the CompletionStage interface. It retrieves the CompletionStageRxInvoker class and allows for these methods to function correctly with the CompletionStage interface return type.

  ACTION BUTTON for QueryResource class here.

  The systemLoad endpoint asynchronously processes the data that is retrieved by the InventoryClient and serves the data when all of the services have responded. The thenAcceptAsync() and exceptionally() methods together behave like an asynchronous try-catch block. The data is processed in the thenAcceptAsync() method only when the CompletionStage interface has finished retrieving it. When you return a CompletionStage type in the resource, it doesn’t necessarily mean that the computation completed and the response was built.

  A CountDownLatch (what?) is used to keep track of how many asynchronous requests are being waited on. The CountDownLatch (what?) countdown towards 0 after the completion of a thread via the countdown method call. This means that the value returns only after the thread that’s retrieving the value is complete. The await method stops and waits until all of the requests have completed. While waiting for this countdown to complete, the main thread is free to perform other tasks. In this case, no such task is present, but a simple task can be given to occupy the thread."

  - [x] (I don't know if all of this CountDownLatch bit is relevant here as I couldn't easily compare the two versions of the file but edit as necessary and put just the changes in the later section.)
  - [x] Avoid using "execute" and "execution".
  - [x] Avoid unnecessary additional words - also 
  - [x] what is a CountDownLatch? there needs to be a noun after the name of something.
  - [x] Don't make every instance of a class/method name into a hotspot - just do it on the first mention in a section/paragraph and again if the highlight has moved to a separate section in the meantime. There's no point the same method highlighted in two consecutive sentences if there hasn't been another hotspot in-between. But, also, make sure you do make the first instance a hotspot (eg the first mention of CompletionStage could be a hotspot here, couldn't it?)
  - [x] stick to present tense when explaining how technology works (eg "the value returns only after", not "will return"). Only use future tense in the context of the reader using the guide (eg you will learn, you will build later in the guide).

Updating the web client to use third-party reactive libraries section
- [x] Change the heading to "Updating the web client to use an alternative reactive provider"
- [x] Then replace the first paragraph with:
  "Although Open Liberty provides the Apache CXF JAX-RS reactive provider by default, you can alternatively use another provider, such as Eclipse Jersey or RESTEasy, which also support the use of RxJava reactive libraries. You'll now update the the web client to use the Jersey reactive provider instead of CXF. This means that you can write clients that use RxJava objects instead of just the CompletionStage interface. These custom objects are useful for covering use cases that the CompletionStage interface cannot. (such as what?)"

- [ ] what does "use specific invokers as configuration" mean? And the earlier client support RxJava so 
- [ ] Is there a better word than "invoker" - that seems an odd word to use. Instead of describing what things are, try to describe what things do and why (it's more succinct and active). And be more active "you can do x" rather than "x can be done" or "x is supported".
- [ ] Can you give an example of a compelling use case rather than just saying vaguely there are some?

Consider here having the user actually update the pom.xml? (ie replace the existing one with the new one then looked at the relevant bits of it) because the libraries wouldn't already be there as dependencies if they really were modifying an existing app.

Then:
- [x] "Update the client…etc (as you have)

  ACTION BUTTON replace etc (as you have)

  The return types of the getSystem() method are now an Observable object instead of a CompletionStage interface. Observable is…. The rx() method now needs to contain RxObservableInvoker.class as an argument. This is to call the specific invoker, RxObservableInvoker, for the Observable class provided by Jersey. In the webTarget() method, the register(RxObservableInvokerProvider) call registers the RxObservableInvoker class, which means that the client can recognize the invoker provider."
- [x] Then your existing paragraph that ends with the link to the blog post.

Updating the REST resource to support the reactive JAX-RS client section
- [x] Use a noun after the name of a thing throughout the guide. eg "the temporary holder class", "inside the subscribe() method"
- [x] Move the bulk of the explanation of the CountDownLatch thing to the first implementation. Just talk here about what's changed in the new implementation.

**Comment by AustinSeto** [comment]
#60 approved and merged, closing this
