### ISSUE TITLE
ID review feedback

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/draft-guide-reactive-rest-client#66]
I added ID review feedback in the attached Word doc. Let me know if you have any questions!

[consuming-restful-reactive-jaxrs.docx](https://github.com/OpenLiberty/draft-guide-reactive-rest-client/files/5110428/consuming-restful-reactive-jaxrs.docx)

**Comment by AustinSeto** [comment]
Closed by #67
