### ISSUE TITLE
Use reactive-rest-client for project ID

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-reactive-rest-client#8]
Use reactive-rest-client for project ID, slug and GH repo.  This aligns better with other guides and is easier to understand.

**Comment by gkwan-ibm** [comment]
@yeekangc do you mean the guide repo name will be guide-reactive-rest-client?

**Comment by yeekangc** [comment]
Yes, the repo name and the slug i.e. the ID we use for the URL.

**Comment by TiagoF99** [comment]
Project id is changed with this pr: https://github.com/OpenLiberty/draft-guide-jax-rs-reactive-client/pull/52

**Comment by yeekangc** [comment]
Should ensure that we classify this guide properly too.

**Comment by gkwan-ibm** [comment]
Addressed in the dev branch
